#!/bin/sh

mkdir -p opk
cp ./PicoDrive opk/PicoDrive
    cp -r ./platform/opendingux/data/skin opk/
cp ./platform/opendingux/data/megadrive.png opk/icon.png

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Picodrive
Comment=MD/GEN Emulator
Exec=PicoDrive
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=false' > opk/default.rs90.desktop

mksquashfs ./opk picodrive_rs90.opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
